language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: iQAPRBVoP549ztjOqWWHYSoXPr6YylCSNDsgg6KAHj0p6vFq1s5PXDqh6mJZjYf476q+mCoHWNVLlaCnx5ZT5XyOGWbF3B04pn0oZRqazbvUfJ0HJG1z4CgkMsYwwC/6TrUL7909Tq+MU2K3AMK78ZHZfH45/4NIZRXi8VmcZDrhWAXj7ArzDBMgLh0r6BuP6N4+SkJ0+UFzDLqN3lmJd4Cz968NaLBYjddkvrppTnFE0bteuOB8O9YT2SAfQVUArgpxhZLrsDqtahiCOHvHR4i4eYqQTrAGtAFBLRIS8HHhw71fODB1pWgdK0v3ucdsBmi1x2wG9FLIz6BH5MYZc4XinykfdzAvwp5fBba/B9Bdo+E9ffFrMpQMVmWf9rTRC5aeXrfefqr40FO/usRgQUpFozc9jqYsngKaJOdWNDKblUhRlS39/Qv1zo+rCHBGMid+Mg7bG7foIcfK3aGp81VzsB6ThEm/6m/OJYE+bDBkdTbpIpveu4VomrSPFsSmgUNxUUBkpciupiX8aTf/MUSiWsAHMwDtbroYPBxNY9FTyOH9COHsS9+c7V9Lg85H4SczWVlyLNf9DaNlbyH2tKz2VUSzagNYHDRpaEtBP9/zKyJ5y31gfe3t0AVyp80xXCyHAF+haAXs798+p5LIuCrAlb5+ngvdSLKZD3SbgfU=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: 2jg20CLUUexeo4sg0NjxPqOlT382d2HdInwKrhomtEwjGaT764HRTYG423V1VMc6hkG8fGLXdO2nTy1qkjneLQhawWIJhMX7Y7sDuKkGn+6SZ7rjz95wLD179wP4VHU99vxeCfvaPOajt+gdckJdpV4j7XoqrkO05aZxsolJ+qnT0MoXgn5fmO+84dFGWsfV9cw+DgcYim9MdEUZkntGf1hgJzKHZvXNL5ilunB4JovROhwXTL3Wl/2qIqzBVLLXzD5tOvneNE+Rc+Dx7gIBO9s/EwD6jF4kYUZktzC8EO05HJyvBQmy3R5dDOddT8tfbPu6MYc7BO1z/3fa/VybOw1wHSb3jdshinXliPzruNPGshRDCCA76vNeKoAVoFNsQ4f005fJk96/Y5OxmS7so/m0p4vrV1eFpHkdXxE6CmusebKaVE15YZlr2KNSANIysR5QcZOOYtQ6qBqjzCBXhzqIoDTgPkKfcZ158eOvqiwVd5+IGN9wMrGAKEsF0ft+QODnLtfyCeGf+LtlxpvnrcLfOmHOoxLPZ6IasaHgXVY8LK9Ey9MHcbppWvW9dpgzU7gQRpcGjh54g3cfOdQx5Ln9ovqhSU/BmWoej9zGq7CKj7pLGE49mQ9l++Ez0LgAp7fMMaGwpNqReIVQIPmrAhfi3cK1E9078dPRx4I3HXI=
sudo: false
