language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: v36abhRXLQU3QARia2wW/P3L+pxR9cA26sYZgDm5K5YIdR1CV7z7o8ksYDdwBT4SX0037zXAmj5ng5BAXirfkZBn3C9HClrrz2jNdYGBUfytsZarinIn6A7QJQ6RVSs0CfzP+VzCAcEXWJJ71V9w9WAzfMjJ5p7TVqr8VAfBc11sHAVNF1lVZKToeqd6MixWIOruPnkgOG4B1HXkezrckX52cIIBslfQQpfqE8i5Iglr92HGMBVM3OZ5exE8jSyYBE6qOiq2lJ3UfCG0VtPr6nhuCKnj0lkGq45j9b2kUFPGz3toozmG9t2T3MKAWxdUMkEl2ymcxxaMTjbvu8X6kBYw5i7zMeW+vvVieDduQLW0LcVeng1yqj8LzmngE5b2E/1Z6r9362bD4QICcci1TyuS+Fh89yCcgk49YzszwuK5/JJ8pAv7MXbq8lMJ/9G3G+/n2NCdzjoKSE4lyX1vGcaDmj4Rvm961u4DLYw/8trOSi33u7JIWihjlNsJ9OQIC56OCNY8INmPoOj/Uk4eH5EEqXPrzUuZDmHPfFAVmvfHP483EaSCpwLYqh5LX7huuI36GWicDNIF6RVQGVsnAYhfzamNLsIlN25JT98uITsvrmoPQVZ3IQI9F42EYhPJrVlR174eyYqlm0cY20fqMUY+wQFuUjvLDZbm5hCxk80=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: W1giN4/ZsY6qqn9sjMOx/bFL2TXWS7P/ncqLIQviVBtXObK7SyRfhg/nqzBQe3cmU3e2fi1qFpk2RrfAKW8kuAYkaNHdGs6r8u1Z1CFqqnYmglHHf0ol2WHMfxQwygn9irSmLi5k3oZjNA+mE9covC5lap3SGsh8QfuNGV5j9ds/+jGoFzaUeZyHbdpOTBN7KhyI6JF2eJ/MTPXFJ+AfwPsCrCjgOmlbolzIqKKmqbllBRQ+wIkvfA/HAZqi3On1NvkYbw95MThwMQ2h82pIvjvlC5uBVfJmvTQ4iSqjj/GNPlch4zo8T/iejVK45KW8ChEGgT1Pf9cMWlYSxt34V4wSrRSBARt7usVVYHs9eoFZgprRHpTJCfYdfyRxkwFw1nEFoCH6TLwIvqA1ZJbA0djcfI8HIz5atT14Our0H85PhQxAQanPiC+kpGzgJq+PL2kiudHwKFMu5O4LVbLdiizNzz1EBnWyQJtXKWz/3qpjHMI13dsuBIrBDg+JebbWC7NgdH+ShyWiGQFxxluu09cVyxU09FuDaS09vrqjO5AUGdCkjSQkbaeDpK3EGaaZlYGhcOD6iDv/TrLmTSXY+iGJ3AvWXajqHEKiZr42eDogpMdc5F2Rg9oTZ3z7rEDQvPK8CsJTfvsAqTqVxUHSlJx0+Yw3qJHpwWWWeBYHPSY=
sudo: false
